# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: todays_campus_development
  username: root
  password: root
  timeout: 5000
  host: 127.0.0.1
  port: 3306